### ISSUE TITLE
FR: Addition of search.json to mack-trucks-regions

### ISSUE THREAD

**Issue by Meli-lazarte** [aemsites/vg-macktrucks-com#206]
### Context
The search.xlsx file needs to be added to all Mack Trucks websites and the required query to index the magazine articles need to be created for each so each magazine entry is added when an article is published.

This needs to be created for the connector to add the published document to OpenSearch.

The config bus query that needs to be added is the following:
```
  search:
    include:
      - '/**'
      - '/mack-news/*/**'
      - '/parts-and-services/support/body-builders/news-and-events/**'
      - '/magazine/articles/*/**'
    exclude:
      - '/drafts/**'
      - 'images/**'
      - '/**/footer'
      - '/footer'
      - '/**/nav'
      - '/nav'
      - '/**/nav-*'
      - '/nav-*'
      - '/**/*-nav'
      - '/*-nav'
      - '/**/sub-nav-*'
      - '/sub-nav-*'
      - '/fragments/**'
      - '/**/sub-nav'
      - '/block-library/**'
      - '/mack-news/fragments/**'
      - '/parts-and-services/support/body-builders/news-and-events/'
      - '/magazine/articles/'
      - '/truck-configurator/'
      - '/truck-configurator/**'
      - '/trucks/anthem/configurator/'
      - '/trucks/granite-series/configurator/'
      - '/trucks/lr-series/configurator/'
      - '/trucks/lr-electric/configurator/'
      - '/trucks/md/configurator/'
      - '/trucks/md-electric/configurator/'
      - '/trucks/pinnacle-series/configurator/'
      - '/trucks/terrapro-series/configurator/'
      - '/trucks/anthem/configurator/**'
      - '/trucks/granite-series/configurator/**'
      - '/trucks/lr-series/configurator/**'
      - '/trucks/lr-electric/configurator/**'
      - '/trucks/md/configurator/**'
      - '/trucks/md-electric/configurator/**'
      - '/trucks/pinnacle-series/configurator/**'
      - '/trucks/terrapro-series/configurator/**'
    target: /search.json
    properties:
      title:
        select: head > meta[property="og:title"]
        value: attribute(el, "content")
      description:
        select: head > meta[name="description"]
        value: attribute(el, "content")
      text:
        select: main
        value: textContent(el)
      url:
        select: head > meta[property="og:url"]
        value: attribute(el, "content")
      locale:
        select: head > meta[name="locale"]
        value: attribute(el, "content")
      tags:
        select: head > meta[property="article:tag"]
        values: attribute(el, "content")
      category:
        select: head > meta[name="category"]
        value: attribute(el, "content")
      articleCategory:
        select: head > meta[name="article-category"]
        value: attribute(el, "content")
      truck:
        select: head > meta[name="truck"]
        value: attribute(el, "content")
      topic:
        select: head > meta[name="topic"]
        value: attribute(el, "content")
      readTime:
        select: head > meta[name="readingtime"]
        value: attribute(el, "content")
      author:
        select: head > meta[name="author"]
        value: attribute(el, "content")
      lastModified:
        select: none
        value: parseTimestamp(headers["last-modified"], "ddd, DD MMM YYYY hh:mm:ss GMT")
      image:
        select: head > meta[property="og:image"]
        value: match(attribute(el, "content"), "https:\/\/[^/]+(/.*)")
      publishDate:
        select: head > meta[name="publish-date"]
        value: parseTimestamp(attribute(el, "content"), MM/DD/YYYY)
```

### AC

- [ ] search.xlsx needs to be created in the root of each MackTrucks Market folder and published
- [ ] The search query needs to be added to each MackTrucks Market folder
- [ ] The `helix-searchConfig` needs to be configured in the constants.json and published

### Websites
- [x] [Australia](https://www.macktrucks.com.au/) macktrucks-com-au
- [x] [Argentina](https://www.macktrucks.com.ar/) macktrucks-com-ar
- [x] [Mexico](https://www.macktrucks.com.mx/) macktrucks-com-mx
- [x] [New Zealand](https://www.macktrucks.co.nz/) macktrucks-co-nz
- [x] [Bolivia](https://www.macktrucks.com.bo/) macktrucks-com-bo
- [x] [Canada](https://www.macktrucks.ca/) macktrucks-ca
- [x] [Colombia](https://www.macktrucks.com.co/) macktrucks-com-co
- [x] [Chile](https://www.macktrucks.cl/) macktrucks-cl
- [x] [Ecuador](https://www.macktrucks.com.ec/) macktrucks-com-ec
- [x] [Guyana](https://www.macktrucksguyana.com/) macktrucks-com-gy
- [x] [Peru](https://www.macktrucks.com.pe/) macktrucks-com-pe
- [x] [Venezuela](https://www.macktrucks.com.ve/) macktrucks-com-ve
- [x] [Dominican Republic](https://www.macktrucks.com.do/)  macktrucks-com-do
- [x] [Haiti](https://www.macktrucks.ht/) macktrucks-ht
- [x] [Costa Rica](https://www.macktrucks.cr/) macktrucks-cr
- [x] [Guatemala](https://www.macktrucks.gt/) macktrucks-gt
- [x] [Honduras](https://www.macktrucks.hn/) macktrucks-hn
- [x] [Nicaragua](https://www.macktrucksnicaragua.com/) macktrucks-com-ni
- [x] [Panama](https://www.macktrucks.com.pa/) macktrucks-com-pa
- [x] [EMEA](https://www.macktrucksemea.com/) macktrucks-com-emea
- [x] [Trinidad & Tobago](https://tt.macktrucks.com/) macktrucks-tt
- [x] [Bahamas](https://bahamas.macktrucks.com/) macktrucks-bs
- [x] [El Salvador](https://sv.macktrucks.com/) macktrucks-sv
- [x] [Nigeria](https://www.macktrucksnigeria.com/) macktrucks-com-ng

### Out of scope: 
- [ ] Every Magazine article needs to be published to be indexed in the search.json index (CONTENT)
